name: macos

on:
  schedule:
    - cron: "0 0 * 1 *"
  push:
    branches:
      - master
    paths:
      - .gitmodules
      - .github/workflows/macos.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
  pull_request:
    paths:
      - .gitmodules
      - .github/workflows/macos.yml
      - CMakeLists.txt
      - CMake/**
      - src/**

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Upgrading CMake
      run: |
        brew upgrade cmake
        cmake --version

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Init Git Submodules
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: git submodule update --init --recursive

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON -DCODE_COVERAGE=${{matrix.coverage}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
