name: ubuntu

on:
  schedule:
    - cron: "0 0 * 1 *"
  push:
    branches:
      - master
    paths:
      - .gitmodules
      - .github/workflows/ubuntu.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
  pull_request:
    paths:
      - .gitmodules
      - .github/workflows/ubuntu.yml
      - CMakeLists.txt
      - CMake/**
      - src/**

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
    - uses: actions/checkout@v2

    - name: Install GCC11
      shell: bash
      run:  |
            sudo apt update
            sudo apt install gcc-11 g++-11

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add Bincrafters Remote
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Init Git Submodules
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: git submodule update --init --recursive

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON
      env:
        CC:   gcc-11
        CXX:  g++-11

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
