name: windows

on:
  push:
    branches:
      - master
    paths:
      - .gitmodules
      - .github/workflows/windows.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/** 
  pull_request:
    paths:
      - .gitmodules
      - .github/workflows/windows.yml
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Add custom conan repo
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake .. "-GVisual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
